services:
  mongo:
    image: mongo
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn run start:dev reservations
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
