apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/sleepr-413506/auth/production
          name: auth
          imagePullPolicy: Never
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: MONGODB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: databaseName
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecret
            - name: JWT_EXPIRES_IN
              value: '3600'
            - name: SERVICE_NAME
              value: auth
            - name: TCP_PORT
              value: '3002'
            - name: HTTP_PORT
              value: '3003'
          ports:
            - containerPort: 3002
            - containerPort: 3003
